//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bl4ckb0t.Modules.CookieRewards {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CookieRewards.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:&amp;g {0}.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given:&amp;g {0}.
        /// </summary>
        internal static string given {
            get {
                return ResourceManager.GetString("given", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t give yourself cookies..
        /// </summary>
        internal static string givingSelf {
            get {
                return ResourceManager.GetString("givingSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough cookies..
        /// </summary>
        internal static string notEnough {
            get {
                return ResourceManager.GetString("notEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received:&amp;g {0}.
        /// </summary>
        internal static string received {
            get {
                return ResourceManager.GetString("received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gave {1} cookies to {2}..
        /// </summary>
        internal static string sent {
            get {
                return ResourceManager.GetString("sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%cookie &lt;username&gt; [amount].
        /// </summary>
        internal static string syntax_cookie {
            get {
                return ResourceManager.GetString("syntax_cookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%cookies [username].
        /// </summary>
        internal static string syntax_cookies {
            get {
                return ResourceManager.GetString("syntax_cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users can give and receive cookies from others. Everybody starts off with 20 cookies.
        /// </summary>
        internal static string usage1 {
            get {
                return ResourceManager.GetString("usage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%cookie &lt;username&gt; || Gives the given user one cookie.
        /// </summary>
        internal static string usage2 {
            get {
                return ResourceManager.GetString("usage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%cookie &lt;username&gt; &lt;amount&gt; || Gives the given user the given amount of cookies.
        /// </summary>
        internal static string usage3 {
            get {
                return ResourceManager.GetString("usage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%cookies &lt;username&gt; || Shows cookie stats of the given user.
        /// </summary>
        internal static string usage4 {
            get {
                return ResourceManager.GetString("usage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%cookies || Shows cookie stats for oneself.
        /// </summary>
        internal static string usage5 {
            get {
                return ResourceManager.GetString("usage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie stats for:&amp;g {0}.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
    }
}
