//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bl4ckb0t.Modules.Remind {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Remind.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time left for &quot;{0}&quot;: {1}.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} active reminders: {1}.
        /// </summary>
        internal static string list {
            get {
                return ResourceManager.GetString("list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, the ID assigned to your reminder for &quot;{1}&quot; is now {2}..
        /// </summary>
        internal static string newId {
            get {
                return ResourceManager.GetString("newId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any active reminders..
        /// </summary>
        internal static string noneActive {
            get {
                return ResourceManager.GetString("noneActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not your reminder..
        /// </summary>
        internal static string noPermission {
            get {
                return ResourceManager.GetString("noPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This reminder does not exist..
        /// </summary>
        internal static string notExisting {
            get {
                return ResourceManager.GetString("notExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, reminder for: {1}.
        /// </summary>
        internal static string reminder {
            get {
                return ResourceManager.GetString("reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, your reminder for &quot;{1}&quot; was {2} ago..
        /// </summary>
        internal static string reminderOver {
            get {
                return ResourceManager.GetString("reminderOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder with ID {0} successfully stopped..
        /// </summary>
        internal static string stopped {
            get {
                return ResourceManager.GetString("stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ll remind you! (ID: {0}).
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%remind &lt;time|stop|id&gt; &lt;remindOf|id&gt;.
        /// </summary>
        internal static string syntax {
            get {
                return ResourceManager.GetString("syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days {1} hours {2} minutes and {3} seconds.
        /// </summary>
        internal static string timeFormat {
            get {
                return ResourceManager.GetString("timeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%remind 1d1h1m1s abc def || Sends you a reminder message about &quot;abc def&quot; in 1 day 1 hour 1 minute and 1 second.
        /// </summary>
        internal static string usage1 {
            get {
                return ResourceManager.GetString("usage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%remind &lt;id&gt; || Sends you info about the reminder with the given id, if found.
        /// </summary>
        internal static string usage2 {
            get {
                return ResourceManager.GetString("usage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%remind stop &lt;id&gt; || Stops the reminder with the given id, if found.
        /// </summary>
        internal static string usage3 {
            get {
                return ResourceManager.GetString("usage3", resourceCulture);
            }
        }
    }
}
