//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bl4ckb0t.Modules.GitHubInfo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitHubInfo.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;3Additions:&amp;h {0}.
        /// </summary>
        internal static string commit_additions {
            get {
                return ResourceManager.GetString("commit_additions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;6Changed files:&amp;h {0}.
        /// </summary>
        internal static string commit_changedFiles {
            get {
                return ResourceManager.GetString("commit_changedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;4Deletions:&amp;h {0}.
        /// </summary>
        internal static string commit_deletions {
            get {
                return ResourceManager.GetString("commit_deletions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GitHub]&amp;g {0} @ {1}.
        /// </summary>
        internal static string commit_header {
            get {
                return ResourceManager.GetString("commit_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments:&amp;g {0}.
        /// </summary>
        internal static string issue_comments {
            get {
                return ResourceManager.GetString("issue_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by:&amp;g {0}.
        /// </summary>
        internal static string issue_createdBy {
            get {
                return ResourceManager.GetString("issue_createdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GitHub]&amp;g {0} - {1} #{2}.
        /// </summary>
        internal static string issue_header {
            get {
                return ResourceManager.GetString("issue_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        internal static string issue_issue {
            get {
                return ResourceManager.GetString("issue_issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Request.
        /// </summary>
        internal static string issue_pullRequest {
            get {
                return ResourceManager.GetString("issue_pullRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:&amp;g {0}.
        /// </summary>
        internal static string issue_state {
            get {
                return ResourceManager.GetString("issue_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:&amp;g {0}.
        /// </summary>
        internal static string issue_title {
            get {
                return ResourceManager.GetString("issue_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forks:&amp;g {0}.
        /// </summary>
        internal static string repo_forks {
            get {
                return ResourceManager.GetString("repo_forks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GitHub]&amp;g {0} - {1}.
        /// </summary>
        internal static string repo_header {
            get {
                return ResourceManager.GetString("repo_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open issues:&amp;g {0}.
        /// </summary>
        internal static string repo_issues {
            get {
                return ResourceManager.GetString("repo_issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest push:&amp;g {0}.
        /// </summary>
        internal static string repo_latestPush {
            get {
                return ResourceManager.GetString("repo_latestPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main language:&amp;g {0}.
        /// </summary>
        internal static string repo_mainLanguage {
            get {
                return ResourceManager.GetString("repo_mainLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stargazers:&amp;g {0}.
        /// </summary>
        internal static string repo_stargazers {
            get {
                return ResourceManager.GetString("repo_stargazers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching:&amp;g {0}.
        /// </summary>
        internal static string repo_watching {
            get {
                return ResourceManager.GetString("repo_watching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows information and statistics about GitHub commits, issues and repositories upon sending their link in chat.
        /// </summary>
        internal static string usage {
            get {
                return ResourceManager.GetString("usage", resourceCulture);
            }
        }
    }
}
