//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bl4ckb0t.Modules.SpellingCorrection {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpellingCorrection.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was corrected by {1} and meant to say: {2}.
        /// </summary>
        internal static string correctingOther {
            get {
                return ResourceManager.GetString("correctingOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} meant to say: {1}.
        /// </summary>
        internal static string correctingSelf {
            get {
                return ResourceManager.GetString("correctingSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%caps [up|low].
        /// </summary>
        internal static string syntax {
            get {
                return ResourceManager.GetString("syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s/wrongPart/correctPart || Replaces every occurence of wrongPart with correctPart in your latest message.
        /// </summary>
        internal static string usage1 {
            get {
                return ResourceManager.GetString("usage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username, s/wrongPart/correctPart || Replaces every occurence of wrongPart with correctPart in someUser&apos;s latest message.
        /// </summary>
        internal static string usage2 {
            get {
                return ResourceManager.GetString("usage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%caps || Switches the capitalization around for the previous message sent by the user.
        /// </summary>
        internal static string usage3 {
            get {
                return ResourceManager.GetString("usage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%caps up || Switches the capitalization to upper case for your previous message.
        /// </summary>
        internal static string usage4 {
            get {
                return ResourceManager.GetString("usage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%caps low || Switches the capitalization to lower case for your previous message.
        /// </summary>
        internal static string usage5 {
            get {
                return ResourceManager.GetString("usage5", resourceCulture);
            }
        }
    }
}
