//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bl4ckb0t.Modules.Forge {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Forge.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no changelog with the given parameters..
        /// </summary>
        internal static string changelogNotFound {
            get {
                return ResourceManager.GetString("changelogNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forge does not support this Minecraft version..
        /// </summary>
        internal static string incorrectMcVersion {
            get {
                return ResourceManager.GetString("incorrectMcVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no main download with the given parameters..
        /// </summary>
        internal static string mainNotFound {
            get {
                return ResourceManager.GetString("mainNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no MDK download with the given parameters..
        /// </summary>
        internal static string mdkNotFound {
            get {
                return ResourceManager.GetString("mdkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%forge &lt;mcVersion&gt; &lt;latest|rec|recommended&gt; &lt;version|changelog|dlmain|dlmdk&gt;.
        /// </summary>
        internal static string syntax {
            get {
                return ResourceManager.GetString("syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. See log for details..
        /// </summary>
        internal static string unexpectedError {
            get {
                return ResourceManager.GetString("unexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command queries files.minecraftforge.net for Forge versions/downloads..
        /// </summary>
        internal static string usage1 {
            get {
                return ResourceManager.GetString("usage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can define a Minecraft version, of which the Forge website should be queried, for instance: -forge 1.7.10.
        /// </summary>
        internal static string usage2 {
            get {
                return ResourceManager.GetString("usage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After that you can define wether you want info to the recommended or latest version of Forge, for instance: -forge 1.7.10 latest.
        /// </summary>
        internal static string usage3 {
            get {
                return ResourceManager.GetString("usage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finally, you define which info you want to have. &quot;changelog&quot; gives you the changelog, &quot;version&quot; the version number,.
        /// </summary>
        internal static string usage4 {
            get {
                return ResourceManager.GetString("usage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;dlmain&quot; the link to the Client/Server installer and &quot;dlmdk&quot; to the Mod Development Kit..
        /// </summary>
        internal static string usage5 {
            get {
                return ResourceManager.GetString("usage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no version with the given parameters..
        /// </summary>
        internal static string versionNotFound {
            get {
                return ResourceManager.GetString("versionNotFound", resourceCulture);
            }
        }
    }
}
