//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bl4ckb0t {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("bl4ckb0t.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version could not be found.
        /// </summary>
        internal static string changelog_notFound {
            get {
                return ResourceManager.GetString("changelog_notFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%changelog [version].
        /// </summary>
        internal static string changelog_syntax {
            get {
                return ResourceManager.GetString("changelog_syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%changelog || Shows the changelog of the current version.
        /// </summary>
        internal static string changelog_usage1 {
            get {
                return ResourceManager.GetString("changelog_usage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%changelog &lt;version&gt; || Shows the changelog of the given version.
        /// </summary>
        internal static string changelog_usage2 {
            get {
                return ResourceManager.GetString("changelog_usage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;k&amp;f(Aliases: .
        /// </summary>
        internal static string help_aliases {
            get {
                return ResourceManager.GetString("help_aliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel commands:.
        /// </summary>
        internal static string help_channelCommands {
            get {
                return ResourceManager.GetString("help_channelCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;aMade by bl4ckscor3.
        /// </summary>
        internal static string help_credits1 {
            get {
                return ResourceManager.GetString("help_credits1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;aThanks Stackoverflow - It saved me many, many times.
        /// </summary>
        internal static string help_credits2 {
            get {
                return ResourceManager.GetString("help_credits2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;aCompiled in .NET 4.5 using ChatSharp (https://github.com/SirCmpwn/ChatSharp).
        /// </summary>
        internal static string help_credits3 {
            get {
                return ResourceManager.GetString("help_credits3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;aSuggestions are much appreciated! Please create a card on the Trello board if you want to submit one :) (-trello).
        /// </summary>
        internal static string help_credits4 {
            get {
                return ResourceManager.GetString("help_credits4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;h&amp;7----------Credits----------.
        /// </summary>
        internal static string help_creditsHeader {
            get {
                return ResourceManager.GetString("help_creditsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;h&amp;7----------Installed modules----------.
        /// </summary>
        internal static string help_genericHelpHeader {
            get {
                return ResourceManager.GetString("help_genericHelpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;h&amp;7----------Help for: {0}----------.
        /// </summary>
        internal static string help_moduleHelpHeader {
            get {
                return ResourceManager.GetString("help_moduleHelpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write -help &lt;module&gt; to get more specific help on that module.
        /// </summary>
        internal static string help_moreInfo {
            get {
                return ResourceManager.GetString("help_moreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string help_none {
            get {
                return ResourceManager.GetString("help_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permission.
        /// </summary>
        internal static string help_noPermission {
            get {
                return ResourceManager.GetString("help_noPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        internal static string help_notesHeader {
            get {
                return ResourceManager.GetString("help_notesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private commands:.
        /// </summary>
        internal static string help_privateCommands {
            get {
                return ResourceManager.GetString("help_privateCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%help &lt;modulename&gt;.
        /// </summary>
        internal static string help_syntax {
            get {
                return ResourceManager.GetString("help_syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%help || Shows all modules and credits.
        /// </summary>
        internal static string help_usage1 {
            get {
                return ResourceManager.GetString("help_usage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%help &lt;modulename&gt; || Shows help to the specified module (the name is seen in -help).
        /// </summary>
        internal static string help_usage2 {
            get {
                return ResourceManager.GetString("help_usage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:.
        /// </summary>
        internal static string help_usageHeader {
            get {
                return ResourceManager.GetString("help_usageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:&amp;g bl4ckscor3.
        /// </summary>
        internal static string info_author {
            get {
                return ResourceManager.GetString("info_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build date:&amp;g {0}.
        /// </summary>
        internal static string info_buildDate {
            get {
                return ResourceManager.GetString("info_buildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET version:&amp;g {0}.
        /// </summary>
        internal static string info_dotNetVersion {
            get {
                return ResourceManager.GetString("info_dotNetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%info.
        /// </summary>
        internal static string info_syntax {
            get {
                return ResourceManager.GetString("info_syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uptime:&amp;g {0}.
        /// </summary>
        internal static string info_uptime {
            get {
                return ResourceManager.GetString("info_uptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows information about the bot.
        /// </summary>
        internal static string info_usage {
            get {
                return ResourceManager.GetString("info_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:&amp;g {0}.
        /// </summary>
        internal static string info_version {
            get {
                return ResourceManager.GetString("info_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This module has already been disabled..
        /// </summary>
        internal static string moduleManagement_alreadyDisabled {
            get {
                return ResourceManager.GetString("moduleManagement_alreadyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This module is already enabled..
        /// </summary>
        internal static string moduleManagement_alreadyEnabled {
            get {
                return ResourceManager.GetString("moduleManagement_alreadyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module has been successfully disabled..
        /// </summary>
        internal static string moduleManagement_disabled {
            get {
                return ResourceManager.GetString("moduleManagement_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module has been successfully enabled..
        /// </summary>
        internal static string moduleManagement_enabled {
            get {
                return ResourceManager.GetString("moduleManagement_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while downloading the module from the URL. See log for details..
        /// </summary>
        internal static string moduleManagement_errorDownloading {
            get {
                return ResourceManager.GetString("moduleManagement_errorDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module was not enabled due to an error. See log for details..
        /// </summary>
        internal static string moduleManagement_errorEnabling {
            get {
                return ResourceManager.GetString("moduleManagement_errorEnabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while loading the module. See log for details..
        /// </summary>
        internal static string moduleManagement_errorLoading {
            get {
                return ResourceManager.GetString("moduleManagement_errorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module was loaded successfully..
        /// </summary>
        internal static string moduleManagement_loaded {
            get {
                return ResourceManager.GetString("moduleManagement_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This module is a private module or doesn&apos;t exist..
        /// </summary>
        internal static string moduleManagement_private {
            get {
                return ResourceManager.GetString("moduleManagement_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem while disabling the module. See log for details..
        /// </summary>
        internal static string moduleManagement_problemDisabling {
            get {
                return ResourceManager.GetString("moduleManagement_problemDisabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem while enabling the module. See log for details..
        /// </summary>
        internal static string moduleManagement_problemEnabling {
            get {
                return ResourceManager.GetString("moduleManagement_problemEnabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem while removing the module. See log for details..
        /// </summary>
        internal static string moduleManagement_problemRemoving {
            get {
                return ResourceManager.GetString("moduleManagement_problemRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module was removed successfully..
        /// </summary>
        internal static string moduleManagement_removed {
            get {
                return ResourceManager.GetString("moduleManagement_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%module &lt;enable|disable|remove|delete|reload|load&gt; &lt;modulename|directDownloadLink&gt;.
        /// </summary>
        internal static string moduleManagement_syntax {
            get {
                return ResourceManager.GetString("moduleManagement_syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%module enable &lt;modulename&gt; || Enables the given module, if it is present in the modules folder.
        /// </summary>
        internal static string moduleManagement_usage1 {
            get {
                return ResourceManager.GetString("moduleManagement_usage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%module disable &lt;modulename&gt; || Disables the given module, if it is present in the modules folder.
        /// </summary>
        internal static string moduleManagement_usage2 {
            get {
                return ResourceManager.GetString("moduleManagement_usage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%module &lt;remove|delete&gt; &lt;modulename&gt;|| Deletes a module from the modules folder.
        /// </summary>
        internal static string moduleManagement_usage3 {
            get {
                return ResourceManager.GetString("moduleManagement_usage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%module reload &lt;modulename&gt; || Reloads a module (disables and enables it again).
        /// </summary>
        internal static string moduleManagement_usage4 {
            get {
                return ResourceManager.GetString("moduleManagement_usage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%module load &lt;directDownloadLink&gt; || Downloads and enables a module from the given link.
        /// </summary>
        internal static string moduleManagement_usage5 {
            get {
                return ResourceManager.GetString("moduleManagement_usage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, {0}, you&apos;re not allowed to do this..
        /// </summary>
        internal static string notAuthorized {
            get {
                return ResourceManager.GetString("notAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%restart.
        /// </summary>
        internal static string shutdown_syntax_restart {
            get {
                return ResourceManager.GetString("shutdown_syntax_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%stop.
        /// </summary>
        internal static string shutdown_syntax_stop {
            get {
                return ResourceManager.GetString("shutdown_syntax_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%stop || Stops the bot without restarting it.
        /// </summary>
        internal static string shutdown_usage1 {
            get {
                return ResourceManager.GetString("shutdown_usage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%restart || Restarts the bot.
        /// </summary>
        internal static string shutdown_usage2 {
            get {
                return ResourceManager.GetString("shutdown_usage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%source.
        /// </summary>
        internal static string source_syntax {
            get {
                return ResourceManager.GetString("source_syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives you the link to the sourcecode of the bot.
        /// </summary>
        internal static string source_usage {
            get {
                return ResourceManager.GetString("source_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%trello.
        /// </summary>
        internal static string trello_syntax {
            get {
                return ResourceManager.GetString("trello_syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the link to the bot&apos;s Trello board.
        /// </summary>
        internal static string trello_usage {
            get {
                return ResourceManager.GetString("trello_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lists were updated successfully..
        /// </summary>
        internal static string update_success {
            get {
                return ResourceManager.GetString("update_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %cmd%update.
        /// </summary>
        internal static string update_syntax {
            get {
                return ResourceManager.GetString("update_syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates all lists (changelog, permissions, channels etc.).
        /// </summary>
        internal static string update_usage {
            get {
                return ResourceManager.GetString("update_usage", resourceCulture);
            }
        }
    }
}
